superhero_project/superhero_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/'))
]

superhero_project/superheroes/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from .import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:hero_id>/', views.detail, name='detail'),
    path('new/', views.create, name='create'),
    path('delete/<int:hero_id_delete>/', views.delete, name ='delete'),
    path('edit/', views.create, name= 'edit'),
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name
        

superhero_project/superheroes/views.py
# from superhero_project import superheroes
# from superhero_project import superheroes
from superhero_project import superheroes
from django.db.models.query_utils import select_related_descend
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        cathchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego =alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=cathchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def delete(request, hero_id_delete):
    delete_hero = Superhero.objects.get(pk=hero_id_delete)
    context = {
        'delete_hero': delete_hero
    }
    if request.method == "POST":
        delete_hero.delete()
        redirect: index.html
    else:
        return render(request, 'superheroes/delete.html', context)
    return render(request, 'superheroes/delete.html', context)
    

def edit(request, hero_id_edit):
    edit_hero = Superhero.objects.get(pk=hero_id_edit)
    context = {
        'edit_hero': edit_hero
    }

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type ="text" name="name" id="name"><br />
        Alter Ego: <input type ="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type ="text" name="primary" id="primary"><br />
        Secondary Ability: <input type ="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type ="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="Add!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Your Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:delete' delete_hero.id %}" method="POST">
        {% csrf_token %}
        Name: <input type ="text" name="name" id="name"><br />
        <input type="submit" value="Delete!">
    </form>
    
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero index</title>
</head>
<body>
    <h1>Your picked Hero</h1>
    <ul>

        <li> <h2> Hero ID: {{single_hero.id}} </h2> </li>
        <li> <h2> Name: {{single_hero.name}} </h2> </li>
        <li> <h2> Alter Ego:{{single_hero.alter_ego}} </h2> </li>
        <li> <h2> Primary Ability: {{single_hero.primary_ability}} </h2> </li>
        <li> <h2> Secondary Ability: {{single_hero.secondary_ability}} </h2> </li>
        <li> <h2> CatchPhrase: {{single_hero.catch_phrase}} </h2> </li>

    </ul>
</body>
</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'superheroes:edit' edit_hero.id %}" method="POST">
        {% csrf_token %}
        Name: <input type ="text" name="name" id="name"><br />
        <input type="submit" value="Edit!">
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes %}
        <li> <h2> {{hero.name}} - <a href="{% url 'superheroes:detail' hero.id%}"> Click for Details</a></h2> </li>
        <a href="{% url 'superheroes:delete' hero.id %}">Delete a Hero</a>
        {% endfor %}
    </ul>
    <a href="{% url 'superheroes:create' %}"> Add New Hero</a> <br />
</body>
</html>